DROP TABLE E_INCLUSO;
DROP TABLE APPROVVIGIONAMENTO;
DROP TABLE E_COMPOSTO;
DROP TABLE COLORE_MONTATURA;
DROP TABLE MONTATURA;
DROP TABLE TRATTAMENTO_LENTE;
DROP TABLE LENTE_CATALOGO;
DROP TABLE INCLUDE;
DROP TABLE MATERIALE_PRODOTTO;
DROP TABLE PRODOTTO;
DROP TABLE FORNITURA;
DROP TABLE TELEFONO_FORNITORE;
DROP TABLE FORNITORE;
DROP TABLE CONSEGNA;
DROP TABLE ORDINE;
DROP TABLE PRESCRIZIONE;
DROP TABLE VISITA_OCULISTICA_EFFETTUATA;
DROP TABLE VISITA_OCULISTICA_PRENOTATA;
DROP TABLE CLIENTE;
DROP TABLE RISPETTA;
DROP TABLE TURNO;
DROP TABLE CONTRATTO;
DROP TABLE IMPIEGATO;
DROP TABLE OCULISTA;
DROP TABLE TELEFONO_DIP;
DROP SEQUENCE MATRICOLE;
DROP TABLE DIPENDENTE;
DROP TABLE PUNTO_VENDITA;

CREATE TABLE PUNTO_VENDITA (
CITTA 			VARCHAR2(20) 		PRIMARY KEY,
ORARIO_APERTURA 	VARCHAR2(5)		NOT NULL,
ORARIO_CHIUSURA 	VARCHAR2(5)		NOT NULL,
VIA 			VARCHAR2(20) 		NOT NULL,
NUM			NUMBER			NOT NULL,
CAP 			CHAR (5) 		UNIQUE NOT NULL,
CORRIERE_APP 		VARCHAR2(20),
COSTO_TOTALE 		NUMBER 		NOT NULL,
CONSTRAINT CHECK_CIVICO CHECK (NUM > 0));

CREATE TABLE DIPENDENTE (
MATRICOLA 		VARCHAR2(5) 		PRIMARY KEY,
CITTA_PV 		VARCHAR2(20) 		NOT NULL,
NOME 			VARCHAR2(20) 		NOT NULL,
COGNOME 		VARCHAR2(20) 		NOT NULL,
SESSO 			CHAR (1) 		NOT NULL,
DATA_NASCITA 		DATE 			NOT NULL,
CF 			CHAR (16) 		UNIQUE NOT NULL,
VIA 			VARCHAR2(20)		NOT NULL,
NUM			NUMBER			NOT NULL,
CAP 			CHAR (5)		NOT NULL,
CONSTRAINT FK_LAVORA FOREIGN KEY (CITTA_PV) REFERENCES PUNTO_VENDITA(CITTA) ON DELETE SET NULL,
CONSTRAINT CHECK_SESSO CHECK (SESSO IN ('M','F')));

/* Creazione della sequenza delle matricole per i dipendenti */
CREATE SEQUENCE MATRICOLE
START WITH 100
INCREMENT BY 1;

CREATE TABLE TELEFONO_DIP (
MATRICOLA_DIP 	VARCHAR2(5),
NUM_TEL_DIP 		CHAR (10),
CONSTRAINT PK_TELEFONO_DIP PRIMARY KEY (MATRICOLA_DIP, NUM_TEL_DIP),
CONSTRAINT FK_DIPENDENTE FOREIGN KEY (MATRICOLA_DIP) REFERENCES DIPENDENTE(MATRICOLA) ON DELETE CASCADE);

CREATE TABLE OCULISTA (
MATRICOLA_OCULISTA 	VARCHAR2(5) 	PRIMARY KEY,
NUM_ISCRIZIONE_ALBO 	CHAR (6) 	NOT NULL,
CONSTRAINT FK_DIP_OC FOREIGN KEY (MATRICOLA_OCULISTA) REFERENCES DIPENDENTE(MATRICOLA) ON DELETE CASCADE);

CREATE TABLE IMPIEGATO (
MATRICOLA_IMP 	VARCHAR2(5) 		PRIMARY KEY,
MANSIONE 		VARCHAR2(25) 		NOT NULL,
CONSTRAINT FK_IMP FOREIGN KEY (MATRICOLA_IMP) REFERENCES DIPENDENTE(MATRICOLA) ON DELETE CASCADE,
CONSTRAINT CHECK_MANSIONE CHECK (MANSIONE IN ('GESTORE_DEI_CLIENTI','MAGAZZINIERE','GESTORE_FORNITORI')));

CREATE TABLE CONTRATTO (
MATRICOLA_DIPENDENTE 	VARCHAR2(5),
DATA_ASSUNZIONE 		DATE,
STIPENDIO 			NUMBER 		NOT NULL,
SCADENZA 			DATE,
TIPO 				VARCHAR2(15) 		NOT NULL,
DURATA				VARCHAR2(10)		NOT NULL,
CONSTRAINT PK_CONTRATTO PRIMARY KEY (MATRICOLA_DIPENDENTE, DATA_ASSUNZIONE),
CONSTRAINT FK_STIPULA FOREIGN KEY (MATRICOLA_DIPENDENTE) REFERENCES DIPENDENTE(MATRICOLA),
CONSTRAINT CHECK_TIPO_CONT CHECK (TIPO IN ('DETERMINATO','INDETERMINATO')),
CONSTRAINT CHECK_DURATA_CONT CHECK (DURATA IN ('PART-TIME','FULL-TIME')),
CONSTRAINT CHECK_SCADENZA_CONT CHECK (SCADENZA > DATA_ASSUNZIONE OR SCADENZA IS NULL));

CREATE TABLE TURNO (
CODICE 		VARCHAR2(20) 		PRIMARY KEY,
ORA_INIZIO 		VARCHAR2(5)		NOT NULL,
NUM_ORE 		NUMBER 		DEFAULT 8 NOT NULL,
CONSTRAINT CHECK_CODICE CHECK(CODICE IN('TURNOOCFT', 'TURNOOCPT1','TURNOOCPT2','TURNOIMPFT','TURNOIMPPT1','TURNOIMPPT2')));

CREATE TABLE RISPETTA (
MATRICOLA_DIP 		VARCHAR2(5),
COD_TURNO 			VARCHAR2(20),
DATA_ORA_INGRESSO 		DATE 		NOT NULL,
DATA_ORA_USCITA 		DATE,
CONSTRAINT PK_RISPETTA PRIMARY KEY (MATRICOLA_DIP, COD_TURNO),
CONSTRAINT FK_DIP FOREIGN KEY (MATRICOLA_DIP) REFERENCES DIPENDENTE(MATRICOLA) ON DELETE CASCADE,
CONSTRAINT FK_TURNO FOREIGN KEY (COD_TURNO) REFERENCES TURNO(CODICE) ON DELETE CASCADE,
CONSTRAINT CHECK_DATA_ORA_USCITA CHECK (DATA_ORA_USCITA > DATA_ORA_INGRESSO));

CREATE TABLE CLIENTE (
TELEFONO 	CHAR (10) 		PRIMARY KEY,
NOME 		VARCHAR2(20) 		NOT NULL,
COGNOME 	VARCHAR2(20) 		NOT NULL,
CF_CLIENTE	CHAR (16) 		UNIQUE NOT NULL);

CREATE TABLE VISITA_OCULISTICA_PRENOTATA (
TELEFONO_CLIENTE	CHAR (10),
DATA_ORA 		DATE,
CONSTRAINT PK_VISITA_OCULISTICA_PRENOTATA PRIMARY KEY (TELEFONO_CLIENTE, DATA_ORA),
CONSTRAINT FK_CLIENTE FOREIGN KEY(TELEFONO_CLIENTE) REFERENCES CLIENTE(TELEFONO));

CREATE TABLE VISITA_OCULISTICA_EFFETTUATA (
MATRICOLA_OCULISTA 		VARCHAR2(5),
DATA_ORA_INIZIO 		DATE,
DATA_ORA_FINE			DATE,
TEL_CLIENTE 			CHAR (10) 	NOT NULL,
DATA_ORA_VISITA_PREN 	DATE 		NOT NULL,
CONSTRAINT PK_VISITA_OC_EFF PRIMARY KEY (MATRICOLA_OCULISTA, DATA_ORA_INIZIO),
CONSTRAINT FK_VISITA_OC_PREN FOREIGN KEY (TEL_CLIENTE, DATA_ORA_VISITA_PREN) REFERENCES VISITA_OCULISTICA_PRENOTATA (TELEFONO_CLIENTE, DATA_ORA),
CONSTRAINT CHECK_DATA_ORA_FINE CHECK (DATA_ORA_FINE > DATA_ORA_INIZIO));

CREATE TABLE PRESCRIZIONE (
ID 		VARCHAR2(8) 		PRIMARY KEY,
TIPO 		VARCHAR2(20)		NOT NULL,
SFERA_OD 	NUMBER,
SFERA_OS 	NUMBER,
CILINDRO_OD 	NUMBER,
CILINDRO_OS 	NUMBER,
ASSE_OD 	NUMBER,
ASSE_OS 	NUMBER,
MAT_OC 	VARCHAR2(5) 		NOT NULL,
D_O_INIZIO 	DATE 			NOT NULL,
CONSTRAINT FK_SI_OTTIENE FOREIGN KEY (MAT_OC, D_O_INIZIO) REFERENCES VISITA_OCULISTICA_EFFETTUATA (MATRICOLA_OCULISTA, DATA_ORA_INIZIO) ON DELETE CASCADE,
CONSTRAINT CHECK_TIPO CHECK (TIPO IN ('DISTANZA', 'PERMANENZA', 'VICINO')),
CONSTRAINT CHECK_ASSE_OD CHECK (ASSE_OD BETWEEN 0 AND 180),
CONSTRAINT CHECK_ASSE_OS CHECK (ASSE_OS BETWEEN 0 AND 180));

CREATE TABLE ORDINE (
NUMERO_ORDINE 	VARCHAR2(10) 		PRIMARY KEY,
MAT_IMP 		VARCHAR2(5) 		NOT NULL,
DATA			DATE			NOT NULL,
ID_PRESCRIZIONE 	VARCHAR2(8) 		NOT NULL,
SCONTO 		NUMBER,
PREZZO_TOTALE 	NUMBER 		NOT NULL,
ANTICIPO 		NUMBER 		DEFAULT 0,
CONSTRAINT FK_EFFETTUA FOREIGN KEY (MAT_IMP) REFERENCES IMPIEGATO(MATRICOLA_IMP) ON DELETE CASCADE,
CONSTRAINT FK_PROCEDE FOREIGN KEY (ID_PRESCRIZIONE) REFERENCES PRESCRIZIONE(ID) ON DELETE CASCADE,
CONSTRAINT CHECK_ANTICIPO CHECK (ANTICIPO <= PREZZO_TOTALE),
CONSTRAINT CHECK_SCONTO CHECK (SCONTO BETWEEN 10 AND 70));

CREATE TABLE CONSEGNA (
CODICE_SCONTRINO 	VARCHAR2(5) 		PRIMARY KEY,
NUMERO_ORD 		VARCHAR2(10) 		NOT NULL,
DATA_CONSEGNA 	DATE 			NOT NULL,
SALDO 			NUMBER 		NOT NULL,
CONSTRAINT FK_SEGUE FOREIGN KEY (NUMERO_ORD) REFERENCES ORDINE(NUMERO_ORDINE) ON DELETE CASCADE);

CREATE TABLE FORNITORE (
P_IVA 			CHAR (11) 	PRIMARY KEY,
NOME_FORNITORE 	VARCHAR2(20) 	NOT NULL);

CREATE TABLE TELEFONO_FORNITORE (
P_IVA_FORN 		CHAR (11),
TEL_FORN 		CHAR (10),
CONSTRAINT PK_TELEFONO_FORNITORE PRIMARY KEY (P_IVA_FORN, TEL_FORN),
CONSTRAINT FK_FORNITORE FOREIGN KEY (P_IVA_FORN) REFERENCES FORNITORE(P_IVA));

CREATE TABLE FORNITURA (
CODICE_FORNITURA 		VARCHAR2(10) 		PRIMARY KEY,
P_IVA_FORN 			CHAR (11) 		NOT NULL,
MATRICOLA_IMPIEGATO 		VARCHAR2(5) 		NOT NULL,
DATA_ORA_PARTENZA 		DATE,
DATA_ORA_ARRIVO 		DATE,
COSTO_TRASPORTO 		NUMBER 		NOT NULL,
CORRIERE 			VARCHAR2(15),
CONSTRAINT FK_GESTISCE FOREIGN KEY (MATRICOLA_IMPIEGATO) REFERENCES IMPIEGATO(MATRICOLA_IMP) ON DELETE SET NULL,
CONSTRAINT FK_FORNISCE FOREIGN KEY (P_IVA_FORN) REFERENCES FORNITORE(P_IVA) ON DELETE CASCADE,
CONSTRAINT CHECK_DATA_ORA_PARTENZA CHECK (DATA_ORA_PARTENZA < DATA_ORA_ARRIVO));

CREATE TABLE PRODOTTO (
CODICE_A_BARRE 		CHAR (13) 		PRIMARY KEY,
PREZZO_ACQUISTO 		NUMBER 		NOT NULL,
PREZZO_VENDITA 		NUMBER 		NOT NULL);

CREATE TABLE MATERIALE_PRODOTTO (
COD_A_BARRE_P 	CHAR (13),
MATERIALE 		VARCHAR2(20),
CONSTRAINT PK_MATERIALE_PRODOTTO PRIMARY KEY (COD_A_BARRE_P, MATERIALE),
CONSTRAINT FK_PRODOTTO FOREIGN KEY (COD_A_BARRE_P) REFERENCES PRODOTTO(CODICE_A_BARRE) ON DELETE CASCADE);

CREATE TABLE INCLUDE (
CODICE_FORN 		VARCHAR2(10),
CODICE_PRODOTTO 	CHAR (13),
QUANTITA_ACQUISTATA 	NUMBER		 NOT NULL,
CONSTRAINT PK_INCLUDE PRIMARY KEY (CODICE_FORN, CODICE_PRODOTTO),
CONSTRAINT FK_PROD FOREIGN KEY (CODICE_PRODOTTO) REFERENCES PRODOTTO(CODICE_A_BARRE) ON DELETE CASCADE,
CONSTRAINT FK_FORNITURA FOREIGN KEY (CODICE_FORN) REFERENCES FORNITURA(CODICE_FORNITURA) ON DELETE CASCADE);

CREATE TABLE LENTE_CATALOGO (
COD_A_BARRE_LENTE 		CHAR (13) 		PRIMARY KEY,
TIPO_LENTE 			VARCHAR2(10)		NOT NULL,
CONSTRAINT FK_LENTE FOREIGN KEY (COD_A_BARRE_LENTE) REFERENCES PRODOTTO(CODICE_A_BARRE) ON DELETE CASCADE,
CONSTRAINT CHECK_TIPO_LENTE CHECK (TIPO_LENTE IN('DA_VISTA','DA_SOLE')));

CREATE TABLE TRATTAMENTO_LENTE (
CODICE_A_BARRE_LENTE 	CHAR (13),
TRATTAMENTO 			VARCHAR2(20),
CONSTRAINT PK_TRATTAMENTO_LENTE PRIMARY KEY (CODICE_A_BARRE_LENTE, TRATTAMENTO),
CONSTRAINT FK_LENTE_CATALOGO FOREIGN KEY (CODICE_A_BARRE_LENTE) REFERENCES LENTE_CATALOGO(COD_A_BARRE_LENTE) ON DELETE CASCADE);

CREATE TABLE MONTATURA (
COD_A_BARRE_MONT 	CHAR (13) 	PRIMARY KEY,
MARCA 			VARCHAR2(20),
MODELLO 		VARCHAR2(20),
CONSTRAINT FK_MONT FOREIGN KEY (COD_A_BARRE_MONT) REFERENCES PRODOTTO(CODICE_A_BARRE) ON DELETE CASCADE);

CREATE TABLE COLORE_MONTATURA (
CODICE_A_BARRE_MONT 		CHAR (13),
COLORE 			VARCHAR2(20),
CONSTRAINT PK_COLORE_MONTATURA PRIMARY KEY (CODICE_A_BARRE_MONT, COLORE),
CONSTRAINT FK_MONTATURA FOREIGN KEY (CODICE_A_BARRE_MONT) REFERENCES MONTATURA(COD_A_BARRE_MONT) ON DELETE CASCADE);

CREATE TABLE E_COMPOSTO (
NUMERO_ORD 		VARCHAR2(10),
COD_BARRE_LENTE 	CHAR (13),
COD_BARRE_MONT 	CHAR (13),
CONSTRAINT PK_E_COMPOSTO PRIMARY KEY (NUMERO_ORD, COD_BARRE_LENTE, COD_BARRE_MONT),
CONSTRAINT FK_LENTE_ORDINE FOREIGN KEY (COD_BARRE_LENTE) REFERENCES LENTE_CATALOGO(COD_A_BARRE_LENTE) ON DELETE SET NULL,
CONSTRAINT FK_MONT_ORDINE FOREIGN KEY (COD_BARRE_MONT) REFERENCES MONTATURA (COD_A_BARRE_MONT) ON DELETE SET NULL,
CONSTRAINT FK_ORDINE FOREIGN KEY (NUMERO_ORD) REFERENCES ORDINE(NUMERO_ORDINE) ON DELETE CASCADE);

CREATE TABLE APPROVVIGIONAMENTO (
CITTA_PV 			VARCHAR2(20),
DATA_ORA_PARTENZA_APP 	DATE,
DATA_ORA_ARRIVO_APP 		DATE,
CONSTRAINT PK_APPROVVIGIONAMENTO PRIMARY KEY (CITTA_PV, DATA_ORA_PARTENZA_APP),
CONSTRAINT FK_ARRIVA FOREIGN KEY (CITTA_PV) REFERENCES PUNTO_VENDITA (CITTA) ON DELETE CASCADE,
CONSTRAINT CHECK_DATA_ORA_PART_APP CHECK (DATA_ORA_PARTENZA_APP < DATA_ORA_ARRIVO_APP));

CREATE TABLE E_INCLUSO (
CODICE_A_BARRE_PROD 		CHAR (13),
DATA_APP 			DATE,
CITTA_PV_APP 			VARCHAR2(20),
QUANTITA_TRASPORTATA 	NUMBER	NOT NULL,		
CONSTRAINT PK_E_INCLUSO PRIMARY KEY (CODICE_A_BARRE_PROD, DATA_APP, CITTA_PV_APP),
CONSTRAINT FK_PROD_APP FOREIGN KEY (CODICE_A_BARRE_PROD) REFERENCES PRODOTTO(CODICE_A_BARRE) ON DELETE CASCADE,
CONSTRAINT FK_APPROVVIGIONAMENTO FOREIGN KEY (DATA_APP, CITTA_PV_APP) REFERENCES APPROVVIGIONAMENTO (DATA_ORA_PARTENZA_APP, CITTA_PV) ON DELETE CASCADE);