-- VISTA 1: VISUALIZZA VISITE PRENOTATE PER PUNTO VENDITA
CREATE OR REPLACE VIEW VISIT_PRENOTATE AS  
SELECT O.MATRICOLA_OCULISTA, D.CITTA_PV, VP.DATA_ORA, C.NOME, C.COGNOME, C.TELEFONO
FROM ((((VISITA_OCULISTICA_PRENOTATA VP JOIN CLIENTE C ON VP.TELEFONO_CLIENTE=C.TELEFONO)JOIN VISITA_OCULISTICA_EFFETTUATA VE ON VE.TEL_CLIENTE= VP.TELEFONO_CLIENTE)JOIN OCULISTA O ON VE.MATRICOLA_OCULISTA=O.MATRICOLA_OCULISTA) JOIN DIPENDENTE D ON D.MATRICOLA=O.MATRICOLA_OCULISTA)
WHERE VP.DATA_ORA>=SYSDATE 
GROUP BY O.MATRICOLA_OCULISTA,D.CITTA_PV,VP.DATA_ORA,C.TELEFONO,C.NOME,C.COGNOME;

-- VISTA 2: VISUALIZZA LA QUANTITA' VENDUTA PER OGNI PRODOTTO
CREATE OR REPLACE VIEW VENDITE_anno AS
SELECT EC.COD_BARRE_LENTE, COUNT(EC.COD_BARRE_LENTE) AS NUM_LENTE, EC.COD_BARRE_MONT, COUNT(EC.COD_BARRE_MONT) AS NUM_MONT
FROM E_COMPOSTO EC JOIN ORDINE O ON EC.NUMERO_ORD=O.NUMERO_ORDINE
WHERE (O.DATA>(SYSDATE-365))
GROUP BY EC.COD_BARRE_LENTE,EC.COD_BARRE_MONT;

-- VISTA 3: VISUALIZZA L'INCASSO ANNUO DELLE VENDITE PER PUNTO VENDITA
CREATE OR REPLACE VIEW INCASSO_ANNUO AS
SELECT D.CITTA_PV, SUM(PREZZO_TOTALE) AS INCASSO
FROM ORDINE O JOIN DIPENDENTE D ON O.MAT_IMP=D.MATRICOLA
WHERE O.DATA > TRUNC(SYSDATE , 'YEAR') 
AND O.DATA < TRUNC(SYSDATE , 'YEAR')+365
GROUP BY D.CITTA_PV;

-- VISTA 4: VISUALIZZA I PRODOTTI DISPONIBILI PER OGNI NEGOZIO
CREATE OR REPLACE VIEW PRODOTTI_DISPONIBILI AS
SELECT EI.Citta_PV_app, P.Codice_a_barre, P.Prezzo_Vendita, COUNT(P.CODICE_A_BARRE) AS NUM_PRODOTTI
FROM E_INCLUSO EI JOIN PRODOTTO P ON EI.CODICE_a_BARRE_PROD=P.CODICE_A_BARRE  
GROUP BY EI.Citta_PV_app, P.Codice_a_barre, P.Prezzo_Vendita;

-- VISTA 5: VISUALIZZA GLI ORDINI CHE DEVONO ESSERE ANCORA CONSEGNATI
CREATE OR REPLACE VIEW ORDINI_NON_CONSEGNATI AS
SELECT O.NUMERO_ORDINE, C.DATA_CONSEGNA, C.SALDO, O.PREZZO_TOTALE 
FROM ORDINE O JOIN CONSEGNA C ON O.NUMERO_ORDINE=C.NUMERO_ORD
WHERE C.DATA_CONSEGNA>SYSDATE;

-- VISTA 6: VISUALIZZA I PRODOTTO IN MAGAZZINO CON RELATIVE QUANTITA'
CREATE OR REPLACE VIEW mostra_forn as
SELECT p.codice_a_barre,NVL(
((SELECT SUM(i2.quantita_acquistata)
FROM fornitura f2 join include i2 on f2.codice_fornitura=i2.codice_forn
WHERE f2.data_ora_arrivo < = to_char(sysdate, 'dd/mon/yyyy') AND i2.codice_prodotto= p.codice_a_barre
     GROUP BY i2.codice_prodotto)
               -
     NVL((SELECT SUM(e.quantita_trasportata)
     FROM e_incluso e
WHERE e.codice_a_barre_prod = p.codice_a_barre
     GROUP BY e.codice_a_barre_prod), 0)), 0) as quantita_magaz
FROM prodotto p;

-- VISTA 7: VISTA DI APPOGGIO PER TRIGGER LICENZIAMENTO
CREATE OR REPLACE VIEW vw_Dipendente as
SELECT Matricola,Citta_PV,Nome,Cognome,Sesso,Data_nascita,CF,Via,Num,CAP
FROM Dipendente;